service:
  name: decompte

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:UpdateTable
      Resource:
        - { "Fn::GetAtt": ["CodesTable", "Arn" ] }
        - { "Fn::GetAtt": ["UsersTable", "Arn" ] }
        - { "Fn::GetAtt": ["ScoresTable", "Arn" ] }

functions:
  createCode:
    handler: handler.createCode
    events:
      - http:
          path: code
          method: POST
          cors: true
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: POST
          cors: true
  addScore:
    handler: handler.addScore
    events:
      - http:
          path: score
          method: POST
          cors: true

  exportCSV:
    handler: handler.exportCSV
    events:
      - http:
          path: csv/{minDate}/{maxDate}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                minDate: true
                maxDate: true


resources:
  Resources:
    CodesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: codes
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: pseudo
            AttributeType: S
        KeySchema:
          - AttributeName: pseudo
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ScoresTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: scoresStats
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1